### ISSUE TITLE
"ShoppingContent" is not defined

### ISSUE THREAD

**Issue by RobertDeBoerNL** [Brainlabs-Digital/Google-Ads-Scripts#15]
Hi,

Nice script https://github.com/Brainlabs-Digital/Google-Ads-Scripts/blob/master/Monitoring/gmc-disapproval-checker.js
, but get this message:
" ReferenceError: "ShoppingContent" is not defined. Line 57"

Tried some things, but cannot solve this issue.

**Comment by ted-udale** [comment]
Hey Robert,

Thanks for finding the issue, I think because the Shopping Content api is not standard you will need to enable it by going to the Advanced Api's tab in the script editor and enabling 'Shopping Content'.

Let me know how this goes ,
 Ted

**Comment by RobertDeBoerNL** [comment]
Hello Ted, yes that was it, thanks!

**Comment by ted-udale** [comment]
Happy to help!
