### ISSUE TITLE
ReferenceError: "ShoppingContent" is not defined. (file Code.gs, line 61)

### ISSUE THREAD

**Issue by anansewill** [Brainlabs-Digital/Google-Ads-Scripts#28]
Does anyone know what could be causing this error?

**Comment by anansewill** [comment]
ReferenceError: "ShoppingContent" is not defined. (file Code.gs, line 61)

**Comment by anansewill** [comment]
Nevermind. I figured it out. Have to click Advanced APIs on the top bar and enable “Shopping content.”

**Comment by james-d-f** [comment]
Glad to hear you were able to get it working 👍
