### ISSUE TITLE
MCC account issue

### ISSUE THREAD

**Issue by markdev16** [Brainlabs-Digital/Google-Ads-Scripts#33]
9/8/2022 9:38:20 PM	Invalid reporting query: ADGROUP_PERFORMANCE_REPORT. (file Code.gs, line 185)

how to query for MCC accounts.

**Comment by emma-brainlabs** [comment]
Hi @markdev16!

I'm not sure which of our scripts you are running, but Google doesn't allow you to query an MCC and get all the data at once - Google only lets you query individual accounts, and then the data has to be summed up by the script/manually.

Most of our free scripts are not built to be able to do this summation across accounts - they can only be run one account at a time.
