### ISSUE TITLE
Not pulling disapprovals

### ISSUE THREAD

**Issue by cristimay** [Brainlabs-Digital/Google-Ads-Scripts#34]
Hello, I've implemented the GMC Disapproval Checker script in a couple client accounts and although it's pulling the correct number of products in the feed, it's saying there are 0 disapproval, when there are disapprovals in each case. Are you able to help?

**Comment by emma-brainlabs** [comment]
Hi @cristimay,

Thanks for reporting this bug! I've just made an update to the code, so this issue should now be fixed 👍🏻

**Comment by emma-brainlabs** [comment]
(You'll need to take a new copy of the code, paste it back into Google Ads and fill in your setting again in order to get the updated, fixed code)

**Comment by cristimay** [comment]
That's awesome, it's working now, thank you
